theme:
    name: material
    features:
        - navigation.sections
        - toc.integrate
        - search.suggest
        - header.autohide
    palette:
        - scheme: default
          primary: white
          accent: indigo
          media: "(prefers-color-scheme: light)"
          toggle:
             icon: material/weather-night
             name: Switch to dark mode
        - scheme: slate
          primary: black
          accent: amber
          media: "(prefers-color-scheme: dark)"
          toggle:
             icon: material/weather-sunny
             name: Switch to light mode
    icon:
        repo: fontawesome/brands/github
        logo: "material/math-integral-box"
    favicon: "_static/favicon.png"
    custom_dir: "docs/_overrides"

    # These additions are my own custom ones, having modified a partial.
    twitter_name: "@PatrickKidger"
    twitter_url: "https://twitter.com/PatrickKidger"

site_name: Diffrax
site_description: The documentation for the Diffrax software library.
site_author: Patrick Kidger

repo_url: https://github.com/patrick-kidger/diffrax
repo_name: patrick-kidger/diffrax
edit_uri: ""  # No edit button, as some of our pages are in /docs and some in /examples via symlink, so it's impossible for them all to be accurate

strict: true  # Don't allow warnings during the build process

extra_javascript: 
    # TODO: Switch to MathJax v3: https://squidfunk.github.io/mkdocs-material/reference/mathjax
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-AMS_CHTML

extra_css:
    - _static/custom_css.css
    # Awful hack to get the favicon to load.  # TODO: find a proper way to include extra static files.
    - _static/favicon.png

markdown_extensions:
    - pymdownx.arithmatex  # Render LaTeX via MathJax
    - pymdownx.superfences  # Seems to enable syntax highlighting when used with the Material theme.
    - admonition
    - mkautodoc

plugins:
    - search
    - mknotebooks  # Jupyter notebooks

nav:
    - 'index.md'
    - Examples:
        - Neural ODE: 'examples/neural_ode.ipynb'
        - Neural CDE: 'examples/neural_cde.ipynb'
        - Latent ODE: 'examples/latent_ode.ipynb'
        - Continuous Normalising Flow: 'examples/continuous_normalising_flow.ipynb'
        - Symbolic Regression: 'examples/symbolic_regression.ipynb'
        - Stiff ODE: 'examples/stiff_ode.ipynb'
        - Stochastic Gradient Descent: 'examples/stochastic_gradient_descent.ipynb'
    - API:
        - Type terminology: 'api/type_terminology.md'
        - Brownian controls: 'api/brownian.md'
        - Nonlinear solvers: 'api/nonlinear_solver.md'
    - Further Details:
        - 'further_details/faq.md'
        - 'further_details/acknowledgements.md'
