theme:
    name: readthedocs
    prev_next_buttons_location: none
    # Syntax highlighting is done manually instead.
    # - This means the default github-theme CSS isn't loaded.
    # - This means we only load the highlighting for those languages we specify manually.
    highlightjs: false
site_name: Diffrax Documentation
strict: true  # Don't allow warnings during the build process

extra_javascript: 
    # TODO: Switch to MathJax v3.
    # Seems mildly faffy to get arithmatex to work with it so haven't done this.
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-AMS_CHTML
    # Python-only syntax-highlighting from https://highlightjs.org/download/
    - _static/highlight.min.js
    # Needed to enable syntax highlighting.
    - _static/run_highlight.js

extra_css:
    # Syntax highlighting
    - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.5.0/styles/foundation.min.css
    # Tweaks to the navbar. # TODO: would be nice to just use a proper theme
    - _static/custom_css.css

markdown_extensions:
    - pymdownx.arithmatex  # Render LaTeX via MathJax
    - pymdownx.betterem    # Better parsing of **emphasis**
    - pymdownx.superfences

plugins:
    - mknotebooks  # Jupyter notebooks

nav:
    - 'index.md'
    - Examples:
#        - 'examples/neural_ode.ipynb'
#        - 'examples/neural_cde.ipynb'
#        - 'examples/latent_ode.ipynb'
        - 'examples/continuous_normalising_flow.ipynb'
#        - 'examples/symbolic_regression.ipynb'
#        - 'examples/stiff_ode.ipynb'
#        - 'examples/stochastic_gradient_descent.ipynb'
    - Further Details:
        - 'further_details/faq.md'
        - 'further_details/acknowledgements.md'
